version: 2.1

orbs:
  cypress: cypress-io/cypress@1.27.0

parameters:
  repo_path:
    description: the path where the repository is cloned into
    type: string
    default: ~/app

executors:
  node-machine:
    working_directory: << pipeline.parameters.repo_path >>
    docker:
      - image: circleci/node:12.18.0-stretch

  with-chrome-87:
    description: Docker container with Node 12, Cypress dependencies and Chrome 87
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82

jobs:
  checkout_code:
    executor: node-machine
    steps:
      - checkout
      - persist_to_workspace:
          root: << pipeline.parameters.repo_path >>
          paths:
            - .

  lint:
    executor: node-machine
    steps:
      - attach_workspace:
          at: << pipeline.parameters.repo_path >>
      - run:
          name: Run linter
          command: yarn run lint

  install_dependencies:
    executor: node-machine
    steps:
      - attach_workspace:
          at: << pipeline.parameters.repo_path >>
      - restore_cache:
          keys:
            - yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies based on lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
      - persist_to_workspace:
          root: << pipeline.parameters.repo_path >>
          paths:
            - node_modules

  # run_cypress:
  #   executor: cypress-machine
  #   steps:
  #     - attach_workspace:
  #         at: << pipeline.parameters.repo_path >>
  #     - restore_cache:
  #         keys:
  #           - yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
  #           - yarn-packages-{{ arch }}-
  #     - run:
  #         name: Install Cypress dependencies
  #         command: yarn install --frozen-lockfile && yarn cypress install
  #     - run:
  #         name: Verify that Cypress is installed correctly and is executable
  #         command: npx cypress verify
  #     - save_cache:
  #         key: yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
  #         paths:
  #           - ~/.cache/Cypress
  #     - run:
  #         name: Start up the app
  #         command: yarn start
  #         background: true
  #     - run:
  #         name: Waiting for server...
  #         command: yarn wait-on http://localhost:3000 && echo local server ready!
  #     - run:
  #         name: Run e2e tests
  #         command: yarn cypress:run --browser chrome --headed
  #     - store_artifacts:
  #         path: cypress/videos
  #     - store_artifacts:
  #         path: cypress/screenshots

workflows:
  build:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - cypress/run:
          name: Run Cypress tests
          executor: with-chrome-87
          requires:
            - lint
          pre-steps:
            - run: yarn stop-only
          working_directory: << pipeline.parameters.repo_path >>
          yarn: true
          cache-key: yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
          no-workspace: true
          browser: chrome
          start: yarn start
          wait-on: http://localhost:3000
          store_artifacts: true
