# version: 2
# jobs: # we now have TWO jobs, so that a workflow can coordinate them!
#   one: # This is our first job.
#     docker: # it uses the docker executor
#       - image: circleci/ruby:2.4.1 # specifically, a docker image with ruby 2.4.1
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     # Steps are a list of commands to run inside the docker container above.
#     steps:
#       - checkout # this pulls code down from GitHub
#       - run: echo "A first hello" # This prints "A first hello" to stdout.
#       - run: sleep 25 # a command telling the job to "sleep" for 25 seconds.
#   two: # This is our second job.
#     docker: # it runs inside a docker image, the same as above.
#       - image: circleci/ruby:2.4.1
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout
#       - run: echo "A more familiar hi" # We run a similar echo command to above.
#       - run: sleep 15 # and then sleep for 15 seconds.
# # Under the workflows: map, we can coordinate our two jobs, defined above.
# workflows:
#   version: 2
#   one_and_two: # this is the name of our workflow
#     jobs: # and here we list the jobs we are going to run.
#       - one
#       - two

# version: 2
# jobs:
#   one:
#     docker:
#       - image: circleci/ruby:2.4.1
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout
#       - run: echo "A first hello"
#       - run: mkdir -p my_workspace
#       - run: echo "Trying out workspaces" > my_workspace/echo-output
#       - persist_to_workspace:
#           # Must be an absolute path, or relative path from working_directory
#           root: my_workspace
#           # Must be relative path from root
#           paths:
#             - echo-output
#   two:
#     docker:
#       - image: circleci/ruby:2.4.1
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout
#       - run: echo "A more familiar hi"
#       - attach_workspace:
#           # Must be absolute path or relative path from working_directory
#           at: my_workspace

#       - run: |
#           if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
#             echo "It worked!";
#           else
#             echo "Nope!"; exit 1
#           fi
# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two:
#           requires:
#             - one

# version: 2
# jobs:
#   build:
#     docker:
#       - image: cimg/node:15.5.1
#     steps:
#       - checkout
#       - run: node --version
#   checklint:
#     docker:
#       - image: cimg/node:15.5.1
#     steps:
#       - checkout
#       - run: npm install
#       - run: yarn lint
#   check_cypress:
#     docker:
#       - image: cypress/browsers:node12.8.1-chrome78-ff70
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm install wait-on
#       - run:
#           command: npm start
#           background: true
#       - run: yarn run wait-on http://localhost:3000 && echo local server ready! && yarn cypress:run

# workflows:
#   version: 2
#   lint_and_build:
#     jobs:
#       - build
#       - checklint:
#           requires:
#             - build
#       - check_cypress:
#           requires:
#             - checklint

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0

parameters:
  repo_path:
    description: the path where the repository is cloned into
    type: string
    default: ~/repo

executors:
  node-machine:
    working_directory: << pipeline.parameters.repo_path >>
    docker:
      - image: circleci/node:12.18.3

  cypress-machine:
    description: Docker container with Node 12, Cypress dependencies and Chrome 87
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82

jobs:
  checkout_code:
    executor: node-machine
    steps:
      - checkout
      - persist_to_workspace:
          root: << pipeline.parameters.repo_path >>
          paths:
            - .

  lint:
    executor: node-machine
    steps:
      - attach_workspace:
          at: << pipeline.parameters.repo_path >>
      - run:
          name: Run linter
          command: yarn run lint

  install_dependencies:
    executor: node-machine
    steps:
      - attach_workspace:
          at: << pipeline.parameters.repo_path >>
      - restore_cache:
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies based on lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: << pipeline.parameters.repo_path >>
          paths:
            - node_modules

  run_cypress:
    executor: cypress-machine
    steps:
      - attach_workspace:
          at: << pipeline.parameters.repo_path >>
      - restore_cache:
          keys:
            - cypress-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "<< pipeline.parameters.repo_path >>/yarn.lock" }}
      - run:
          command: yarn cypress install
      - run:
          name: Install Cypress dependencies
          command: cd << pipeline.parameters.repo_path >>/cypress && yarn install --frozen-lockfile
      - run:
          name: Verify that Cypress is installed correctly and is executable
          command: cd << pipeline.parameters.repo_path >>/cypress && yarn cypress verify
      - save_cache:
          key: cypress-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "<< pipeline.parameters.repo_path >>/yarn.lock" }}
          paths:
            - ~/.cache/Cypress
      - run:
          name: Start up the app
          command: cd << pipeline.parameters.repo_path >> && yarn start
          background: true
      - run:
          name: Waiting for server...
          command: cd << pipeline.parameters.repo_path >> && yarn wait-on http://localhost:3000 && echo local server ready!
      - run:
          name: Run e2e tests
          command: cd << pipeline.parameters.repo_path >> && yarn cypress:run --browser chrome --headless
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_test_results:
          path: test-results

workflows:
  build:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - run_cypress:
          requires:
            - lint





      # - cypress/install:
      #     requires:
      #       - lint
      # - cypress/run:
      #     requires:
      #       - cypress/install
      #     attach-workspace: true
      #     yarn: true
      #     start: npm start
      #     wait-on: "http://localhost:3000"
      #     store_artifacts: true
      #  - store_test_results:
      #     path: test-results

